package it.derrik.Vista;


import it.derrik.Modello.Deselezionatore;
import java.util.ArrayList;
import javax.swing.JToggleButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author derrik
 */
public class VistaSceltaMazzo extends javax.swing.JPanel {

    /**
     * Creates new form VistaSceltaMazzo
     */
    public VistaSceltaMazzo(String nome) {
        initComponents();
        jLabel1.setText(nome);
        listaBottoni.add(bottoneMago);
        bottoneMago.addItemListener(new Deselezionatore(this, 0));
        listaBottoni.add(bottoneCacciatore);
        bottoneCacciatore.addItemListener(new Deselezionatore(this, 1));
        listaBottoni.add(bottoneDruido);
        bottoneDruido.addItemListener(new Deselezionatore(this, 2));
        listaBottoni.add(bottoneLadro);
        bottoneLadro.addItemListener(new Deselezionatore(this, 3));
        listaBottoni.add(bottonePaladino);
        bottonePaladino.addItemListener(new Deselezionatore(this, 4));
        listaBottoni.add(bottoneSacerdote);
        bottoneSacerdote.addItemListener(new Deselezionatore(this, 5));
        listaBottoni.add(bottoneStregone);
        bottoneStregone.addItemListener(new Deselezionatore(this, 6));
        listaBottoni.add(bottoneSciamano);
        bottoneSciamano.addItemListener(new Deselezionatore(this, 7));
        listaBottoni.add(bottoneGuerriero);
        bottoneGuerriero.addItemListener(new Deselezionatore(this, 8));
        
    }

    private ArrayList<JToggleButton> listaBottoni = new ArrayList<>();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bottoneCacciatore = new javax.swing.JToggleButton();
        bottoneDruido = new javax.swing.JToggleButton();
        bottoneGuerriero = new javax.swing.JToggleButton();
        bottoneLadro = new javax.swing.JToggleButton();
        bottoneMago = new javax.swing.JToggleButton();
        bottonePaladino = new javax.swing.JToggleButton();
        bottoneSacerdote = new javax.swing.JToggleButton();
        bottoneSciamano = new javax.swing.JToggleButton();
        bottoneStregone = new javax.swing.JToggleButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("jLabel1");

        bottoneCacciatore.setText("Cacciatore");

        bottoneDruido.setText("Druido");

        bottoneGuerriero.setText("Guerriero");

        bottoneLadro.setText("Ladro");

        bottoneMago.setText("Mago");

        bottonePaladino.setText("Paladino");

        bottoneSacerdote.setText("Sacerdote");

        bottoneSciamano.setText("Sciamano");

        bottoneStregone.setText("Stregone");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(117, 117, 117))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bottoneSacerdote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bottoneCacciatore, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bottoneLadro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bottoneDruido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bottoneMago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bottoneSciamano, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bottoneGuerriero, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(bottonePaladino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bottoneStregone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bottoneCacciatore)
                    .addComponent(bottoneDruido)
                    .addComponent(bottoneGuerriero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bottoneLadro)
                    .addComponent(bottoneMago)
                    .addComponent(bottonePaladino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bottoneSacerdote)
                    .addComponent(bottoneSciamano)
                    .addComponent(bottoneStregone))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bottoneCacciatore;
    private javax.swing.JToggleButton bottoneDruido;
    private javax.swing.JToggleButton bottoneGuerriero;
    private javax.swing.JToggleButton bottoneLadro;
    private javax.swing.JToggleButton bottoneMago;
    private javax.swing.JToggleButton bottonePaladino;
    private javax.swing.JToggleButton bottoneSacerdote;
    private javax.swing.JToggleButton bottoneSciamano;
    private javax.swing.JToggleButton bottoneStregone;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public ArrayList<JToggleButton> getListaBottoni() {
        return listaBottoni;
    }

    public void setListaBottoni(ArrayList<JToggleButton> listaBottoni) {
        this.listaBottoni = listaBottoni;
    }

    public JToggleButton getBottoneCacciatore() {
        return bottoneCacciatore;
    }

    public void setBottoneCacciatore(JToggleButton bottoneCacciatore) {
        this.bottoneCacciatore = bottoneCacciatore;
    }

    public JToggleButton getBottoneDruido() {
        return bottoneDruido;
    }

    public void setBottoneDruido(JToggleButton bottoneDruido) {
        this.bottoneDruido = bottoneDruido;
    }

    public JToggleButton getBottoneGuerriero() {
        return bottoneGuerriero;
    }

    public void setBottoneGuerriero(JToggleButton bottoneGuerriero) {
        this.bottoneGuerriero = bottoneGuerriero;
    }

    public JToggleButton getBottoneLadro() {
        return bottoneLadro;
    }

    public void setBottoneLadro(JToggleButton bottoneLadro) {
        this.bottoneLadro = bottoneLadro;
    }

    public JToggleButton getBottoneMago() {
        return bottoneMago;
    }

    public void setBottoneMago(JToggleButton bottoneMago) {
        this.bottoneMago = bottoneMago;
    }

    public JToggleButton getBottonePaladino() {
        return bottonePaladino;
    }

    public void setBottonePaladino(JToggleButton bottonePaladino) {
        this.bottonePaladino = bottonePaladino;
    }

    public JToggleButton getBottoneSacerdote() {
        return bottoneSacerdote;
    }

    public void setBottoneSacerdote(JToggleButton bottoneSacerdote) {
        this.bottoneSacerdote = bottoneSacerdote;
    }

    public JToggleButton getBottoneSciamano() {
        return bottoneSciamano;
    }

    public void setBottoneSciamano(JToggleButton bottoneSciamano) {
        this.bottoneSciamano = bottoneSciamano;
    }

    public JToggleButton getBottoneStregone() {
        return bottoneStregone;
    }

    public void setBottoneStregone(JToggleButton bottoneStregone) {
        this.bottoneStregone = bottoneStregone;
    }

    

}
